lib/quest/web/router.ex
defmodule Quest.Web.Router do
  use Quest.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/questionnaires", Quest.Web do
    pipe_through :browser # Use the default browser stack

    resources "/", QuestionnaireController
  end

  scope "/questions", Quest.Web do
    pipe_through :browser # Use the default browser stack

    resources "/", QuestionController
  end

  scope "/options", Quest.Web do
    pipe_through :browser # Use the default browser stack

    resources "/", OptionController
  end

  scope "/submissions", Quest.Web do
    pipe_through :browser # Use the default browser stack

    get "/:uid", SubmissionController, :show
    resources "/", SubmissionController
  end
  
  scope "/", Quest.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/new", PageController, :new
    get "/:slug", PageController, :show
    resources "/", PageController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Quest.Web do
  #   pipe_through :api
  # end
end

lib/quest/web/controllers/questionnaire_controller.ex
defmodule Quest.Web.QuestionnaireController do
  use Quest.Web, :controller

  alias Quest.Main
  import Ecto.{Query, Changeset}, warn: false
  alias Quest.Repo


  def index(conn, _params) do
    questionnaires = Main.list_questionnaires()
    render(conn, "index.html", questionnaires: questionnaires)
  end

  def new(conn, _params) do
    changeset = Main.change_questionnaire(%Quest.Main.Questionnaire{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"questionnaire" => questionnaire_params}) do
    tags = [questionnaire_params["tags"]]
    questionnaire_params = %{questionnaire_params | "tags" => tags}

    case Main.create_questionnaire(questionnaire_params) do
      {:ok, questionnaire} ->
        conn
        |> put_flash(:info, "Questionnaire created successfully.")
        |> redirect(to: questionnaire_path(conn, :show, questionnaire))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    # start stopwatch
    start = Timex.now

    # questionnaire = Repo.get!(Quest.Main.Questionnaire, id)
    # questionnaire = Repo.preload questionnaire, :main_questions

    # questionnaire = Repo.preload questionnaire, main_questions: from(q in Quest.Main.Question, order_by: [asc: q.order]) 

    questionnaire = Main.get_questionnaire!(id)
    changeset = Main.change_submission(%Quest.Main.Submission{})

    editlink = questionnaire_path(conn, :edit, id) 
    finish = Timex.now
    dur = Timex.diff(finish, start, :milliseconds)

    form = true

    render(conn, "show.html", questionnaire: questionnaire, changeset: changeset, editlink: editlink, dur: dur, form: form)
  end

  def edit(conn, %{"id" => id}) do
    questionnaire = Main.get_questionnaire!(id)
    questions = Main.list_questions_of(id)

    changeset = Main.change_questionnaire(questionnaire)
    render(conn, "edit.html", questionnaire: questionnaire, changeset: changeset, questions: questions)
  end

  def update(conn, %{"id" => id, "questionnaire" => questionnaire_params}) do
    questionnaire = Main.get_questionnaire!(id)
    tags = String.split(questionnaire_params["tags"], ",")
    questionnaire_params = %{questionnaire_params | "tags" => tags}
    questions = Main.list_questions_of(id)

    case Main.update_questionnaire(questionnaire, questionnaire_params) do
      {:ok, questionnaire} ->
        conn
        |> put_flash(:info, "Questionnaire updated successfully.")
        |> redirect(to: questionnaire_path(conn, :show, questionnaire))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", questionnaire: questionnaire, changeset: changeset, questions: questions)
    end
  end

  def delete(conn, %{"id" => id}) do
    questionnaire = Main.get_questionnaire!(id)
    {:ok, _questionnaire} = Main.delete_questionnaire(questionnaire)

    conn
    |> put_flash(:info, "Questionnaire deleted successfully.")
    |> redirect(to: questionnaire_path(conn, :index))
  end
end

lib/quest/web/views/questionnaire_view.ex
defmodule Quest.Web.QuestionnaireView do
  use Quest.Web, :view
end

lib/quest/web/templates/questionnaire/edit.html.eex
<h2>Edit Questionnaire <%= @questionnaire.title %></h2>

<%= render "form.html", changeset: @changeset, questions: @questions, conn: @conn, questionnaire: @questionnaire,
                        action: questionnaire_path(@conn, :update, @questionnaire) %>

<span><%= link "Back", to: questionnaire_path(@conn, :index) %></span>
<span><%= link "Show", to: questionnaire_path(@conn, :show, @questionnaire.id) %></span>

lib/quest/web/templates/questionnaire/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :info, class: "control-label" %>
    <%= textarea f, :info, class: "form-control", id: "editor" %>
    <%= error_tag f, :info %>
  </div>

  <div class="form-group">
    <%= label f, :tags, class: "control-label" %>
    <%= text_input f, :tags, value: Enum.join(@questionnaire.tags, ", "), class: "form-control" %>
    <% IO.puts "===" %>
  </div>

  <div class="form-group">
    <%= label f, :status, class: "control-label" %>
    <%= select f, :status, ["Public": "public", "Private": "private", "Unlisted": "unlisted", "Locked": "locked", "Scheduled": "scheduled"], class: "form-control" %>
    <%= error_tag f, :status %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>




<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Info</th>
      <th>Content</th>
      <th>Order</th>
      <th>Type</th>
      <th>Required</th>
      <th>Active</th>
      <th>Inline</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for question <- @questions do %>
      <%  info = HtmlSanitizeEx.strip_tags(question.info) 
              |> String.split
              |> Enum.slice(0..3)
              |> Enum.map(fn(x) -> [x<>" "] end)
              |> List.to_string %>

      <tr>
        <td><%= question.id %></td>
        <td><%= question.title %></td>
        <td><%= info %></td>
        <td><%= question.content %></td>
        <td><%= question.order %></td>
        <td><%= question.type %></td>
        <td><%= question.required %></td>
        <td><%= question.active %></td>
        <td><%= question.inline %></td>

        <td class="text-right">
          <span><%= link "Show", to: question_path(@conn, :show, question), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Edit", to: question_path(@conn, :edit, question), class: "btn btn-default btn-xs" %></span>
          <span><%= link "Delete", to: question_path(@conn, :delete, question), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<span><%= link "New question", to: question_path(@conn, :new, "questionnaire_id": @questionnaire.id) %></span>

lib/quest/web/templates/questionnaire/index.html.eex
<h2>Listing Questionnaires</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Info</th>
      <th>Status</th>
      <th>Tags</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for questionnaire <- @questionnaires do %>
    <tr>
      <td><%= questionnaire.title %></td>
      <td><%= questionnaire.info %></td>
      <td><%= questionnaire.status %></td>
      <td><%= questionnaire.tags %></td>

      <td class="text-right">
        <span><%= link "Show", to: questionnaire_path(@conn, :show, questionnaire), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: questionnaire_path(@conn, :edit, questionnaire), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: questionnaire_path(@conn, :delete, questionnaire), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Questionnaire", to: questionnaire_path(@conn, :new) %></span>

lib/quest/web/templates/questionnaire/new.html.eex
<h2>New Questionnaire</h2>

<%= render "form.html", changeset: @changeset,
                        action: questionnaire_path(@conn, :create) %>

<span><%= link "Back", to: questionnaire_path(@conn, :index) %></span>

lib/quest/web/templates/questionnaire/show.html.eex
<h1><%= @questionnaire.title %></h1>

<div>
  <article><%= raw(@questionnaire.info) %></article>
</div>

<br />

<div class="row items content">
  <div class="item">Status: <span><%= @questionnaire.status %></span></div>
  <div class="item">Tags:
    <%# tags = String.split(@questionnaire.tags, ",") %>
    <% tags = @questionnaire.tags %>

    <%= for tag <- tags do %>
      <span><%= tag %></span>
    <% end %>
  </div>
</div>

<hr />

  <% action = submission_path(@conn, :create) %>
  <%= form_for @changeset, action, [class: "pure-form pure-form-stacked", data_parsley_validate: "", id: "form"], fn f -> %>
  <%#= form_for @changeset, action, [class: "pure-form pure-form-stacked", onsubmit: "return validate(this);"], fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Oops, something went wrong! Please check the errors below.</p>
      </div>
    <% end %> 

    <ul class="questions">
      <%= for question <- @questionnaire.main_questions do %>
        <% content = String.split(String.trim(question.content), ["\r\n", ","]) %>
        <%# title = String.to_atom Slugger.slugify(question.title) %>
        <% title = String.to_atom(Integer.to_string(question.id)) %>
        <% titlestring = question.title %>
        <% if question.required do required? = true else required? = false end %>

        <%= case question.type do %>

          <%# -----TEXT----- %>
          <%= "text" -> %>
            <li class="form-group">
              <%= label f, title, titlestring %>
              <span><%= content %></span>
              <%= if required? do text_input f, title, class: "pure-input-1", id: title, required: ""
                  else text_input f, title, class: "pure-input-1", id: title end %>
              <%#= error_tag f, title %>
            </li>

          <%# -----SPECIAL----- %>
          <%= "special" -> %>
            <li class="form-group">
              <%= label f, title, titlestring %>
              <%= for item <- content do %>
                <% titlecb = String.to_atom Integer.to_string(question.id)<>"."<>item %>
                <div>
                  <%= if required? do select f, titlecb, 1..5, id: title, required: "", style: "inline; width: 4em;"
                      else select f, titlecb, 1..5, id: title, style: "display:inline; width: 4em;" end %>
                  <span style="display:inline;margin-right:1em;"><%= item %></span>
                </div>
              <% end %>
              <%#= error_tag f, title %>
            </li>
          <%# -----TEXTAREA----- %>
          <%= "textarea" -> %>
            <li class="form-group">
              <%= label f, title, titlestring %>
              <span><%= content %></span>
              <%= if required? do textarea f, title, rows: 3, class: "pure-input-1", id: title, required: "", data_parsley_trigger: "keyup", data_parsley_minlength: "10", data_parsley_maxlength: "500", data_parsley_minlength_message: "Unesite minimalno 10 slova/brojeva", data_parsley_maxlength_message: "Unesite maksimalno 500 slova/brojeva",data_parsley_validation_threshold: "10"
                  else textarea f, title, rows: 3, class: "pure-input-1", id: title end %>
              <%#= error_tag f, title %>
            </li>
          <%# -----RADIO----- %>
          <%= "radio" -> %>
            <li class="form-group">
              <%= label f, title, titlestring %>
              <%= for item <- content do %>
                <%= if required? do radio_button f, title, item, id: title, required: ""
                    else radio_button f, title, item, id: title end %>
                    <span style="display:inline-block;margin-right:1em;"><%= item %></span>
              <% end %>
              <%#= error_tag f, title %>
            </li>
          <%# -----OPEN ENDED----- %>
          <%= "open" -> %>
            <li class="form-group">
              <%= label f, title, titlestring %>
              <%= for item <- content do %>
                <div style="display:table-cell;"><%= if required? do radio_button f, title, item, id: title, required: "", class: "disable#{title}"
                    else radio_button f, title, item, id: title, class: "disable#{title}" end %>
                    <span style="display:inline-block;margin-right:1em;"><%= item %></span>   
                </div>
              <% end %>
              <div style="display:block;">

                <%= radio_button f, title, title, class: "disable#{title}", id: title, style: "display:inline-block;margin-right:.5em;" %>Please specify
                <%= text_input f, title, disabled: "disabled", style: "display:inline-block;width:50%;margin-left: .5em;", id: "text#{title}" %>

              </div>
              <%#= error_tag f, title %>
            </li>
          <%# -----TICK----- %>
          <%= "tick" -> %>
            <li class="form-group">
              <%= label f, title, titlestring, class: "header" %>
              <div class="readmore"><%= raw(question.info) %></div>

              <%= for item <- content do %>
                <% titlecb = String.to_atom question.title<>"."<>item %>
                <%= if required? do checkbox f, titlecb, checked_value: true, unchecked_value: false, id: title, required: ""#, data_parsley_mincheck: "2"
                    else checkbox f, titlecb, checked_value: true, unchecked_value: false, id: title end %>
                    <span style="display:inline-block;margin-right:1em;"><%= item %></span>
                <%#= error_tag f, titlecb %>
              <% end %>
            </li>
          <%# -----EMAIL----- %>
          <%= "email" -> %>
            <li class="form-group">
              <%= label f, title, titlestring %>
              <span><%= content %></span>
              <%= if required? do email_input f, title, class: "pure-input-1", id: title, required: ""
                  else email_input f, title, class: "pure-input-1", id: title end %>
              <%#= error_tag f, title %>
            </li>
          <%# -----SELECT----- %>
          <%= "select" -> %>
            <li class="form-group">
              <%= label f, title, titlestring %>
              <%= if required? do select f, title, content, prompt: "Izaberite", class: "pure-input-1", id: title, required: ""
                  else select f, title, content, prompt: "Izaberite", class: "pure-input-1#{required?}", id: title end %>
              <%#= error_tag f, title %>
            </li>
          <%# -----INFO----- %>
          <%= "info" -> %>
            <div>
              <h4><%= titlestring %></h4>
              <em><%= content %></em>
              <%#= if required? do text_input f, title, class: "pure-input-1", id: title, required: ""
                  else text_input f, title, class: "pure-input-1", id: title end %>
            </div>
          <%# -----LIKERT----- %>
          <%= "likert" -> %>
            <li class="form-group">
              <%= label f, title, titlestring %>
              <% [content] = content %>
              <% if TypeCheck.is_numeric(content) do content = String.to_integer content else content = 5 end %>

              <strong>Strongly agree&nbsp;&nbsp;</strong>
              <%= for item <- 1..content do %>
                <%= if required? do radio_button f, title, item, id: title, required: ""
                    else radio_button f, title, item, id: title end %>
                    <span style="display:inline-block;margin-right:1em;"><%= item %></span>
              <% end %>
              <strong>Strongly disagree</strong>
              <%#= error_tag f, title %>
            </li>


        <% end %>
        <%#= question.id %>
        <%#= question.title %>
        <%#= question.vrsta %>
        <%#= question.content %>
        <%#= question.active %>



      <% end %>
    </ul>

      <%= hidden_input f, :questionnaire_id, value: @questionnaire.id %>

      <%= submit "Submit", class: "button" %>
      <%= link "Cancel", to: questionnaire_path(@conn, :index), class: "button button-outline" %>
    <% end %>