lib/quest/web/router.ex
defmodule Quest.Web.Router do
  use Quest.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/questionnaires", Quest.Web do
    pipe_through :browser # Use the default browser stack

    resources "/", QuestionnaireController
  end

  scope "/questions", Quest.Web do
    pipe_through :browser # Use the default browser stack

    resources "/", QuestionController
  end

  scope "/options", Quest.Web do
    pipe_through :browser # Use the default browser stack

    resources "/", OptionController
  end

  scope "/submissions", Quest.Web do
    pipe_through :browser # Use the default browser stack

    get "/:uid", SubmissionController, :show
    resources "/", SubmissionController
  end
  
  scope "/", Quest.Web do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/new", PageController, :new
    get "/:slug", PageController, :show
    resources "/", PageController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Quest.Web do
  #   pipe_through :api
  # end
end

lib/quest/web/views/layout_view.ex
defmodule Quest.Web.LayoutView do
  use Quest.Web, :view
end

lib/quest/web/templates/layout/app-menu.html.eex
<section>
<div class="content" style="padding:0;">
  <ul style="padding:0;">
      <li>
        <%= link "Home", to: page_path(@conn, :index) %>
      </li>
    <%= for page <- pages_menu do %>
      <% [page, slug] = page %>
      <li>
        <%= link page, to: page_path(@conn, :show, slug) %>
      </li>
    <% end %>
  </ul>
</div>
</section>

lib/quest/web/templates/layout/app-splash-home.html.eex
<div>
  <h1>[ Semantic Questionnaires ]</h1>
  <p><i class="ion-android-arrow-forward"></i> <%= link "Click Here for Pilot Study", to: questionnaire_path(@conn, :show, 1) %> <i class="ion-android-arrow-back"></i>
</div>

lib/quest/web/templates/layout/app-splash.html.eex
<div class="logo-container">
  <div class="pure-g">
    <div class="pure-u-md-3-24 pure-u-lg-4-24 pure-u-xl-6-24"></div>
    <div class="pure-u-1 pure-u-md-18-24 pure-u-lg-16-24 pure-u-xl-12-24" style="position: relative;">
      Logo
    </div>
    <div class="pure-u-md-3-24 pure-u-lg-4-24 pure-u-xl-6-24"></div>
  </div>
</div>

<div class="splash-container">
  <div class="splash">
    <div class="pure-g">
      <div class="pure-u-md-1-24"></div>
      <div class="pure-u-1 pure-u-md-23-24" style="position: relative;">
        Quest
      </div>
    </div>
  </div>
</div>

lib/quest/web/templates/layout/app.html.1.eex
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Semantic Quest</title>

  <!-- Styles -->
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>
<body>
<% start = Timex.now %>
<main class="wrapper">
  <nav class="nav">
    <%= render "app-menu.html", view_module: @view_module, conn: @conn %>
  </nav>

  <section class="main">
    <aside class="info"><%= get_flash(@conn, :info) %></aside>
    <aside class="extra"><%= get_flash(@conn, :extra) %></aside>
    <aside class="error"><%= get_flash(@conn, :error) %></aside>
    <div class="content">
      <%= render @view_module, @view_template, assigns %>
    </div>
    <% finish = Timex.now %>
    <% durrend = Timex.diff(finish, start, :microseconds) %>
    <footer>
      Semantic Quest <%= DateTime.utc_now.year %> | <%= if assigns[:dur] do "Query: #{@dur}ms" end %> Rendering: <%= durrend/1000 %>ms <%= if assigns[:editlink] do raw("| <a href='#{@editlink}'>Edit</a>") end %>
    </footer>
  </section>

</main>





<!--<script src="<%= static_path(@conn, "/js/jquery.min.js") %>"></script>-->

<!--  Scripts-->
<%= if assigns[:form] do %>
  <%= if @form do %>
    <script src="<%= static_path(@conn, "/js/parsley.min.js") %>"></script>
    <!--<script src="<%#= static_path(@conn, "/js/i18n/hr.js") %>"></script>-->
    <script src="<%= static_path(@conn, "/js/script-parsley.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/parselyConditions.min.js") %>"></script>
    <script>
      var fValidate = $.parselyConditions({
        
          csstoggle: 'parselyTaDa',
          formname: 'form',
        
          validationfields: [

              {
                  fid: 'question_type',
                  ftype: 'select',
                  fvalue: 'likert',
                  faffected: 'question_content',
                  fhide: 'maskDiv'
              }
          ]

      });
</script>
  <% end %>
<% end %>

<!--<script src="<%= static_path(@conn, "/js/trumbowyg.min.js") %>"></script>
<script src="<%= static_path(@conn, "/js/script-trumb.js") %>"></script>
<script src="<%= static_path(@conn, "/js/readmore.min.js") %>"></script>-->

<script src="<%= static_path(@conn, "/js/app.js") %>"></script>

<!--<script src="<%= static_path(@conn, "/js/script.js") %>"></script>-->



</body>

</html>

lib/quest/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Semantic Quest</title>

  <!-- Styles -->
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>
<body>
<% start = Timex.now %>
<main class="wrapper">
  <nav class="nav">
    <%= render "app-menu.html", view_module: @view_module, conn: @conn %>
  </nav>

  <section class="main">
    <aside class="info"><%= get_flash(@conn, :info) %></aside>
    <aside class="extra"><%= get_flash(@conn, :extra) %></aside>
    <aside class="error"><%= get_flash(@conn, :error) %></aside>
    <div class="content">
      <%= render @view_module, @view_template, assigns %>
    </div>
    <% finish = Timex.now %>
    <% durrend = Timex.diff(finish, start, :microseconds) %>
    <footer>
      Semantic Quest <%= DateTime.utc_now.year %> | <%= if assigns[:dur] do "Query: #{@dur}ms" end %> Rendering: <%= durrend/1000 %>ms <%= if assigns[:editlink] do raw("| <a href='#{@editlink}'>Edit</a>") end %>
    </footer>
  </section>

</main>





<script src="<%= static_path(@conn, "/js/jquery.min.js") %>"></script>

<!--  Scripts-->
<%= if assigns[:form] do %>
  <%= if @form do %>
    <script src="<%= static_path(@conn, "/js/parsley.min.js") %>"></script>
    <!--<script src="<%#= static_path(@conn, "/js/i18n/hr.js") %>"></script>-->
    <script src="<%= static_path(@conn, "/js/script-parsley.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/parselyConditions.min.js") %>"></script>
    <script>
      var fValidate = $.parselyConditions({
        
          csstoggle: 'parselyTaDa',
          formname: 'form',
        
          validationfields: [

              {
                  fid: 'question_type',
                  ftype: 'select',
                  fvalue: 'likert',
                  faffected: 'question_content',
                  fhide: 'maskDiv'
              }
          ]

      });
</script>
  <% end %>
<% end %>

<script src="<%= static_path(@conn, "/js/trumbowyg.min.js") %>"></script>
<script src="<%= static_path(@conn, "/js/script-trumb.js") %>"></script>
<script src="<%= static_path(@conn, "/js/readmore.min.js") %>"></script>

<script src="<%= static_path(@conn, "/js/app.js") %>"></script>

<script src="<%= static_path(@conn, "/js/script.js") %>"></script>



</body>

</html>

lib/quest/web/templates/layout/front.html.eex
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Semantic Quest</title>

  <!-- Styles -->
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  
</head>
<body>
<body>
<% start = Timex.now %>
<main class="wrapper">
  <nav class="home">
    <%= render "app-menu.html", view_module: @view_module, conn: @conn %>
  </nav>

  <section class="splash home">
    <%= render "app-splash-home.html", view_module: @view_module, conn: @conn %>
  </section>

  <section class="main home">
    <aside class="info"><%= get_flash(@conn, :info) %></aside>
    <aside class="extra"><%= get_flash(@conn, :extra) %></aside>
    <aside class="error"><%= get_flash(@conn, :error) %></aside>
    <div class="content">
      <%= render @view_module, @view_template, assigns %>
    </div>
    <% finish = Timex.now %>
    <% durrend = Timex.diff(finish, start, :microseconds) %>
    <footer>
      Semantic Quest <%= DateTime.utc_now.year %> | <%= if assigns[:dur] do "Query: #{@dur}ms" end %> Rendering: <%= durrend/1000 %>ms <%= if assigns[:editlink] do raw("| <a href='#{@editlink}'>Edit</a>") end %>
    </footer>
  </section>

</main>



<!--  Scripts-->
<%= if assigns[:form] do %>
  <%= if @form do %>
    <script src="<%= static_path(@conn, "/js/parsley.min.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/i18n/hr.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/script-parsley.js") %>"></script>
  <% end %>
<% end %>

<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script src="<%= static_path(@conn, "/js/jquery.min.js") %>"></script>
<!--<script src="<%= static_path(@conn, "/js/script.js") %>"></script>-->


</body>
</html>